name: .NET

# Runs on general and C#-specific branches only, including in pull requests
on:
  push:
    branches:
      - main
      - 'release/**'
      - 'cs/**'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./C#/
    - name: Build
      run: dotnet build ./C#/ --no-restore
    - name: Test
      run: dotnet test ./C#/ --no-build -v n
